#!/bin/bash
set -euo pipefail

HERE=$(dirname "$0")
C2PULSE="$(realpath $HERE/external/llvm-project/build/bin/c2pulse)"
FSTAR_BIN="$(realpath $HERE/external/FStar/bin/fstar.exe)"
PULSE_DIR="$(realpath $HERE/external/pulse/out/lib/pulse)"
PULSE_LIB_C_DIR="$(realpath $HERE/include/pulse)"

# Check input
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <source1.c> [source2.c ...] [--log <logfile>]"
  exit 1
fi

echo "Processing input files: $@"

# Parse optional --log argument (very simple approach)
LOG_FILE=""
POSITIONAL_ARGS=()

# Parse optional arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --log)
      shift
      if [[ $# -gt 0 ]]; then
        LOG_FILE="$1"
        shift
      else
        echo "Error: --log requires a filename"
        exit 1
      fi
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

# Restore positional arguments (source files etc.)
set -- "${POSITIONAL_ARGS[@]}"


# Prepare the command invocation as a variable for reuse
CMD=( $C2PULSE "$@" \
  --extra-arg-before=-DC2PULSE \
)

# Run command, capture output and optionally save to log
if [[ -n "$LOG_FILE" ]]; then
  # Save full output to log file AND pipe to awk for extraction
  # Using tee to write output to the log file while also piping
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | tee "$LOG_FILE" | awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
else
  # Just capture the output without logging
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | tee /dev/stderr | awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
fi

# Check if files were found
if [ "${#SRC_FILES[@]}" -eq 0 ]; then
  echo "No .fst or .fsti files generated by c2pulse."
  exit 1
fi

echo "Generated Pulse files:"
for file in "${SRC_FILES[@]}"; do
  echo "  $file"
done

# Run fstar on all files at once
exec "$FSTAR_BIN" \
  --include "$PULSE_DIR" \
  --include "$PULSE_LIB_C_DIR" \
  --query_stats --z3version 4.13.3 \
  "${SRC_FILES[@]}" 
