#!/bin/bash
set -euo pipefail

# System headers
SYSTEM_CC_INCLUDE="/usr/lib/clang/20.1.5/include"
SYSTEM_INCLUDE="/usr/include"
SYSTEM_ARCH_INCLUDE="/usr/include/x86_64-linux-gnu"
C_STD="-std=c23"

# Check input
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <source1.c> [source2.c ...]"
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Processing input files: $@"

# Parse optional --log argument (very simple approach)
LOG_FILE=""
POSITIONAL_ARGS=()

# Parse optional arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --log)
      shift
      if [[ $# -gt 0 ]]; then
        LOG_FILE="$1"
        shift
      else
        echo "Error: --log requires a filename"
        exit 1
      fi
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

# Restore positional arguments (source files etc.)
set -- "${POSITIONAL_ARGS[@]}"


# Prepare the command invocation as a variable for reuse
CMD=( "$SCRIPT_DIR/../external_tools/llvm-project/build/bin/c2pulse" "$@" \
  -p ../external_tools/llvm-project/build/ \
  --extra-arg-before="-resource-dir" \
  --extra-arg-before="../external_tools/llvm-project/build/lib/clang/21" \
  --extra-arg-before="-isystem" \
  --extra-arg-before="$SYSTEM_CC_INCLUDE" \
  --extra-arg-before="-isystem" \
  --extra-arg-before="$SYSTEM_ARCH_INCLUDE" \
  --extra-arg-before="-isystem" \
  --extra-arg-before="$SYSTEM_INCLUDE" \
  --extra-arg-before="-isystem" \
  --extra-arg-before="../external_tools/llvm-project/build/lib/clang/21/include" \
  --extra-arg-before="-x" \
  --extra-arg-before="c" \
  --extra-arg-before="$C_STD" \
  --extra-arg-before="-c" \
  --extra-arg-before=-fmodules \
  --extra-arg-before=-fimplicit-modules \
  --extra-arg-before=-fmodules-cache-path=/tmp/clang-modules )

# Run command, capture output and optionally save to log
if [[ -n "$LOG_FILE" ]]; then
  # Save full output to log file AND pipe to awk for extraction
  # Using tee to write output to the log file while also piping
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | tee "$LOG_FILE" | awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
else
  # Just capture the output without logging
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
fi

# Check if files were found
if [ "${#SRC_FILES[@]}" -eq 0 ]; then
  echo "No .fst or .fsti files generated by c2pulse."
  exit 1
fi

echo "Generated Pulse files:"
for file in "${SRC_FILES[@]}"; do
  echo "  $file"
done

# Path to F* binary
FSTAR_BIN="$SCRIPT_DIR/../external_tools/FStarLang/bin/fstar.exe"

# Run fstar on all files at once
exec "$FSTAR_BIN" \
  --include "$SCRIPT_DIR/../external_tools/pulse/out/lib/pulse" \
  --query_stats --z3version 4.13.3 \
  "${SRC_FILES[@]}" 
