// This C code was generated by CoPilot for testing purposes.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "../../../include/PulseMacros.h"

REQUIRES(pure (Int32.fits (Int32.v x * 3)))
RETURNS(res : Int32.t)
ENSURES(pure (Int32.v x * 3 == Int32.v res))
int triple(int x) { 
    return x * 3; 
}

REQUIRES(pure (Int32.fits (Int32.v x * Int32.v x)))
RETURNS(res : Int32.t)
ENSURES(pure (Int32.v x * Int32.v x == Int32.v res))
int square(int x) { 
    return x * x; 
}

REQUIRES(pure (Int32.fits (Int32.v x * 2)))
RETURNS(res : Int32.t)
ENSURES(pure (Int32.v x * 2 == Int32.v res))
int doubleValue(int x) { 
    return x * 2; 
}


REQUIRES(pure (Int32.fits (Int32.v x + Int32.v y)))
RETURNS(res : Int32.t)
ENSURES(pure (Int32.v x + Int32.v y == Int32.v res))
int sum(int x, int y) { 
    return x + y; 
}

// This is a hack to get this function to pass. To properly
// check this function we need to find some invariant about
// the size of the returned value.
REQUIRES(pure False)
RETURNS(res : Int32.t)
int recursiveFunction(int x, int limit) {
    if (x >= limit) return x;
    else{
        return sum(12,  recursiveFunction(x + 1, limit));
    }
}

// int randomOffset(int x) { 
//     return x + (rand() % 10); 
// }

//From Guido
// Precondition could be more liberal, this is just one
// possibility. User should annotate what they want.
REQUIRES(pure (abs (Int32.v x) < 1000 /\\ abs (Int32.v y) < 1000))
RETURNS(res : Int32.t)
int complexComputation(int x, int y) {
    return square(triple(sum(doubleValue(x), y))) + 
           doubleValue(square(y - x)) /*- randomOffset(sum(x, y))*/;
}

// Vidush: Pulse does not handle for loops at the moment.
// void arrayManipulation(int *arr, int size) {
//     for (int i = 0; i < size; i++) {
//         arr[i] = complexComputation(arr[i], sum(arr[(i + 1) % size], arr[i]));
//         arr[i] = square(arr[i]);
//         arr[i] += 1;
//     }
// }


//From Guido
// Precondition could be more liberal, this is just one
// possibility. User should annotate what they want.
REQUIRES(pure (abs (Int32.v x) < 1000 /\\ abs (Int32.v y) < 1000))
RETURNS(res : Int32.t)
int conditionalProcessing(int x, int y) {
    if ((x * y) % 2 == 0) {
        return sum(triple(x), square(y - x));
    } else {
        return doubleValue(square(sum(x, y))) /*- randomOffset(x)*/;
    }
}

//The recursive function in the below form does not work. 
//Since pulse cannot handle non void returns after if without an else.
//From Guido
// This is a hack to get this function to pass. To properly
// check this function we need to find some invariant about
// the size of the returned value.
// REQUIRES(pure False)
// RETURNS(res : Int32.t)
// int recursiveFunction(int x, int limit) {
//     if (x >= limit) return x;
//     return sum(conditionalProcessing(x, square(x)), recursiveFunction(x + 1, limit));
// }

// int main() {
//     int a = 3, b = 5;
//     int result = complexComputation(a, b);
    
//     int arr[5] = {1, 2, 3, 4, 5};
//     //arrayManipulation(arr, 5);

//     int recursiveResult = recursiveFunction(a, 8);
    
//     printf("Complex Computation Result: %d\n", ((result + 1) + 3));
//     printf("Array after processing: ");
//     // for (int i = 0; i < 5; i++) {
//     //     printf("%d ", arr[i]);
//     // }
//     printf("\nRecursive Computation Result: %d\n", recursiveResult);

//     return 0;
// }