#define REQUIRES(s) [[clang::pulse("requires:"#s"|END")]]
#define ENSURES(s) [[clang::pulse("ensures:"#s"|END")]]
#define RETURNS(s) [[clang::pulse("returns:"#s"|END")]]
#define ISARRAY(len) [[clang::pulse("array:"#len"|END")]]
#define INVARIANTS(...) [[clang::pulse("invariants:"#__VA_ARGS__"|END")]]
#define LEMMA(l) [[clang::pulse("lemma:"#l"|END")]]