module List

#lang-pulse
open Pulse

module Box = Pulse.Lib.Box
open Pulse.Lib.Box { box }

noeq
type node (t:Type0) = {
    head : t;
    tail : option (box (node t));
}

and llist (t:Type0) = option (box (node t))

(* Autogenerated getters/setters for node. They can be given
an impl, but OK to assume. *)
(* NOTE: I am using box here but the general solution should
use ref. The tool should then add steps to turn a box into a 
ref and viceversa. Let's ignore that for the time being. *)
fn node_get_head #t (n : box (node t)) (#v0 : erased (node t))
  preserves n |-> v0
  returns  res : t
  ensures pure (res == v0.head)
{
  (Box.op_Bang n).head;
}

fn node_set_head #t (n : box (node t)) (#v0 : erased (node t)) (head' : t)
  requires n |-> v0
  ensures  n |-> { v0 with head = head' }
{
  let v = Box.op_Bang n;
  Box.op_Colon_Equals n ({ v with head = head' })
}

fn node_get_tail #t (n : box (node t)) (#v0 : erased (node t))
  preserves n |-> v0
  returns   res : option (box (node t))
  ensures   pure (res == v0.tail)
{
  (Box.op_Bang n).tail
}

fn node_set_tail #t (n : box (node t)) (#v0 : erased (node t)) (tail' : option (box (node t)))
  requires n |-> v0
  ensures  n |-> { v0 with tail = tail' }
{
  let v = Box.op_Bang n;
  Box.op_Colon_Equals n ({ v with tail = tail' })
}

(* Hm... we cannot prove termination of this predicate
as it is not decreasing a list in any way. Maybe we should
be define it coinductively? Admit the termination, for now. *)
[@@admit_termination]
let rec list_live #t (x:llist t)
  = match x with
    | None -> emp
    | Some v -> 
      exists* (n : node t).
        pts_to v n **
        list_live n.tail

fn push #t (x : t) (l : llist t)
  requires list_live l
  returns  l' : llist t
  ensures  list_live l'
{
  let n = Box.alloc { head = x; tail = l };
  fold (list_live (Some n));
  Some n
}

fn peek #t (l : llist t)
  requires list_live l 
  requires pure (Some? l)
  returns  x : t
  ensures  list_live l
{
  unfold (list_live l);
  let Some v = l; (* allowed since non-null *)
  let r = node_get_head v;
  fold (list_live (Some v));
  r
}

fn pop #t (l : llist t)
  requires pure (Some? l)
  requires list_live l
  returns  l' : llist t
  ensures  list_live l'
{
  unfold (list_live l);
  let Some v = l;
  let r = node_get_tail v;
  Box.free v;
  r
}

fn is_empty #t (l : llist t)
  requires list_live l
  returns  b : bool
  ensures  list_live l
{
  (None? l)
}
