FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        opam pkg-config libgmp-dev tmux ripgrep tig \
        clang clang-format ccls zstd rustup \
        lsb-release wget software-properties-common gnupg && \
    apt-get clean

RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 20 && \
    apt-get update && \
    apt-get install -y clang-20 libclang-cpp20-dev g++ clang-tools-20 libclang-20-dev && \
    apt-get clean && \
    rm llvm.sh

USER vscode
RUN opam init --bare

RUN rustup install stable

RUN curl -fsSL https://gh.io/copilot-install | bash

RUN opam option depext-run-installs=true
ENV OPAMYES=1
RUN --mount=type=bind,source=.git,destination=/c2p-repo \
    git config --global --add safe.directory /c2p-repo && \
    sudo mkdir /workspaces && sudo chown vscode:vscode /workspaces && \
    cd /workspaces && git clone --depth=1 --recurse-submodules --shallow-submodules --reference-if-able=/c2p-repo --dissociate /c2p-repo c2pulse && \
    cd c2pulse && \
    ./opt/fstar/.scripts/get_fstar_z3.sh ~/.local/bin/ && \
    make -j`nproc` build-pulse && \
    sudo tar --zstd -cf /c2pulse-opt-cache.tar.zst opt .git/modules && \
    cd / && sudo rm -rf /workspaces
