module StackAllocatedStruct
#lang-pulse
open Pulse

//Adapted from this issue:
// https://github.com/FStarLang/c2pulse/issues/28#issuecomment-3046564391

noeq
type point = {
px: ref Int32.t;
py: ref Int32.t;
}

[@@erasable]
noeq
type point_spec = {
px : Int32.t;
py : Int32.t

}

let point_pred (x:ref point) (s:point_spec) : slprop =
exists* (y: point). (x |-> y) **
(y.px |-> s.px) **
(y.py |-> s.py)

assume val point_spec_default : point_spec

assume val point_default (ps:point_spec) : point

ghost
fn point_pack (p:ref point) (#ps:point_spec)
requires p |-> point_default ps
ensures exists* v. point_pred p v ** pure (v == ps)
{ admit() }

ghost
fn point_unpack (p:ref point)
requires exists* v. point_pred p v
ensures exists* u. p |-> u
{ admit() }


ghost fn point_explode (x:ref point) (#s:point_spec)
requires point_pred x s
ensures exists* (v: point). (x |-> v) ** (v.px |-> s.px) ** (v.py |-> s.py)
{unfold point_pred}


ghost
fn point_recover (x:ref point) (#a0 : Int32.t) (#a1 : Int32.t) 
requires exists* (y: point). (x |-> y) ** (y.px |-> a0) ** (y.py |-> a1)
ensures exists* w. point_pred x w ** pure (w == {px = a0; py = a1})
{fold point_pred x ({px = a0; py = a1}) }


fn test_stack_allocator ()
requires emp
ensures emp
{
  let mut p = point_default point_spec_default;
  point_pack p; //generated by front end
  point_explode p;
  (!p).px := 1l;
  (!p).py := 2l;
  point_recover p;
  point_unpack p; //generated by front end
}