#!/bin/bash
set -euo pipefail

HERE="$(dirname "$0")/../"

C2PULSE="$(realpath $HERE/external/llvm-project/build/bin/c2pulse)"
FSTAR_BIN="$(realpath $HERE/external/FStar/bin/fstar.exe)"
PULSE_DIR="$(realpath $HERE/external/pulse/out/lib/pulse)"
PULSE_LIB_C_DIR="$(realpath $HERE/include/pulse)"

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <source1.c> [source2.c ...] [--log <logfile>]"
  exit 1
fi

echo "Processing input: $@"

# Optional --log argument
LOG_FILE=""
POSITIONAL_ARGS=()

# Parse optional arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --log)
      shift
      if [[ $# -gt 0 ]]; then
        LOG_FILE="$1"
        shift
      else
        echo "Error: --log requires a filename"
        exit 1
      fi
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

# Restore positional args
set -- "${POSITIONAL_ARGS[@]}"

# Resolve files and directories into flat list of `.c` files (non-recursive)
C_FILES=()
for input in "$@"; do
  if [[ -f "$input" && "$input" == *.c ]]; then
    C_FILES+=("$input")
  elif [[ -d "$input" ]]; then
    while IFS= read -r -d $'\0' file; do
      C_FILES+=("$file")
    done < <(find "$input" -maxdepth 1 -type f -name "*.c" -print0)
  fi
done

if [ ${#C_FILES[@]} -eq 0 ]; then
  echo "No C source files found."
  exit 1
fi

# Prepare C2Pulse command as a variable for reuse
CMD=(
  $C2PULSE "${C_FILES[@]}" \
  --extra-arg-before=-DC2PULSE
  #--extra-arg-before=-include \
  #--extra-arg-before=$(realpath "$HERE/test/include/PulseMacros.h") \
)

# Run command, capture output and optionally save to log
if [[ -n "$LOG_FILE" ]]; then
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | tee "$LOG_FILE" | awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
else
  mapfile -t SRC_FILES < <(
    "${CMD[@]}" 2>&1 | stdbuf -oL awk '/Print the filename!/ {getline; if ($0 ~ /\.fst[i]?$/) print}'
  )
fi

# Check if files were found
if [ "${#SRC_FILES[@]}" -eq 0 ]; then
  echo "No .fst or .fsti files generated by c2pulse."
  exit 1
fi

echo "Generated Pulse files:"
for file in "${SRC_FILES[@]}"; do
  echo "  $file"
done

echo "${SRC_FILES[@]}"

echo "Running F* on generated files..."
fstar_output=$("$FSTAR_BIN" \
  --include "$PULSE_DIR" \
  --include "$PULSE_LIB_C_DIR" \
  --query_stats --z3version 4.13.3 \
  "${SRC_FILES[@]}" 2>&1)

echo "$fstar_output"

# Check for VC success
if echo "$fstar_output" | grep -q "All verification conditions discharged successfully"; then
  echo -e "✔ All VCs discharged."
else
  echo -e "❌ Verification failed."
  exit 1
fi

echo "Checking if the generated file matches the expected output."
for file in "${SRC_FILES[@]}"; do
 echo "  Checking file: $file"

  # Extract the base name and capitalize it for snapshot comparison
  name="$(basename "$file")"        
  capitalized="${name^}"    
  snapshot="$(realpath "$HERE/test/snapshots/$capitalized")"        

  echo "  Checking: [ $file ] against snapshot [ $snapshot ]"

  if diff_output=$(diff -u "$file" "$snapshot"); then
    echo "    ✔ OK: $file matches snapshot."
  else
    echo "    ❌ Mismatch found in $file!"
    echo "$diff_output"
    exit 1
  fi
  echo "    ✔ Snapshot check passed for $file"
done
exit 0
echo "All files processed successfully."
