name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, Linux, X64, c2pulse]
    steps:
    - name: Clean
      run: find . -delete

    - uses: actions/checkout@v3
    - uses: cda-tum/setup-z3@main
      with:
        version: 4.13.3
    - name: Get submodules
      run: |
        git submodule init
        git submodule update --depth 1

    - name: Read submodule commit hashes
      id: commits
      run: |
        C=$(git -C external/FStar rev-parse HEAD)
        echo "FSTARCOMMIT=$C" >>"$GITHUB_OUTPUT"
        C=$(git -C external/pulse rev-parse HEAD)
        echo "PULSECOMMIT=$C" >>"$GITHUB_OUTPUT"
 
    # - name: Set-up OCaml
    #   uses: ocaml/setup-ocaml@v3
    #   with:
    #     ocaml-compiler: 5

    - name: Install some dependencies
      run: |
        cat /etc/lsb-release
        sudo apt update
        sudo apt install -y libclang-cpp19-dev
    #     opam install --deps-only external/FStar/fstar.opam

    - name: Try fetch built F*
      id: cache-fstar
      uses: actions/cache/restore@v4
      with:
        path: external/FStar
        key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.commits.outputs.FSTARCOMMIT }}

    - name: Build F*
      if: steps.cache-fstar.outputs.cache-hit != 'true'
      run: |
        eval $(opam env)
        make -C external/FStar -skj$(nproc) ADMIT=1

    - name: Save built F*
      if: steps.cache-fstar.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: external/FStar
        key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.commits.outputs.FSTARCOMMIT }}

    - name: Try fetch built Pulse
      id: cache-pulse
      uses: actions/cache/restore@v4
      with:
        path: external/pulse
        key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.commits.outputs.FSTARCOMMIT}}-${{ steps.commits.outputs.PULSECOMMIT }}

    - name: Build Pulse
      if: steps.cache-pulse.outputs.cache-hit != 'true'
      run: |
        eval $(opam env)
        make -C external/pulse -skj$(nproc) ADMIT=1 FSTAR_EXE=$(pwd)/external/FStar/bin/fstar.exe

    - name: Save built Pulse
      if: steps.cache-pulse.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: external/pulse
        key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.commits.outputs.FSTARCOMMIT}}-${{ steps.commits.outputs.PULSECOMMIT }}

    - name: Build c2pulse
      run: |
        eval $(opam env)
        ./build.sh

    - name: Save ccache, again
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ccache
        key: ccache-${{ runner.os }}-${{ runner.arch }}

    - name: Run tests
      run: |
        eval $(opam env)
        ./test_runner.sh
